import type {
  AgentDef,
  InjectionMark,
  ToolDef,
  ToolCall,
  Trace,
  TraceStep,
} from "@asp-x/shared";
import type { LLMProvider } from "../llm/types.js";

/** Result of applying an attack hook at a single-string channel. */
export interface InjectionResult {
  /** Possibly modified content. If unchanged, just pass the original. */
  content: string;
  /** Optional annotation for the trace, identifying the injection. */
  injection?: InjectionMark;
}

/** Result of applying an attack hook at the memory-entries channel. */
export interface MemoryInjectionResult {
  entries: string[];
  injection?: InjectionMark;
}

/**
 * The framework taps these four channels to play the role of "environment"
 * around the agent. Each is optional — provide only the ones the attack uses.
 */
export interface AttackHook {
  onSystemPrompt?(prompt: string): InjectionResult;
  onUserTask?(task: string): InjectionResult;
  onMemoryEntries?(entries: string[]): MemoryInjectionResult;
  onObservation?(toolName: string, content: string): InjectionResult;
}

/**
 * Defenses wrap the same channels. They can rewrite, filter, or augment.
 * A wrapper returning the original content is a no-op.
 */
export interface DefenseHook {
  wrapSystemPrompt?(prompt: string): string;
  wrapUserTask?(task: string): string;
  wrapObservation?(toolName: string, content: string): string;
  /** Return false to suppress the observation entirely. */
  filterObservation?(toolName: string, content: string): boolean;
}

/** Optional in-memory context for the agent (simulated RAG). */
export interface MemoryContext {
  entries: string[];
}

export interface RunnerOptions {
  agent: AgentDef;
  task: string;
  tools: ToolDef[];
  provider: LLMProvider;
  model: string;
  attack?: AttackHook;
  defense?: DefenseHook;
  memory?: MemoryContext;
  maxSteps?: number;
  temperature?: number;
  abortSignal?: AbortSignal;
  /** Streaming callback fired after each TraceStep is appended. */
  onStep?: (step: TraceStep) => void;
  /** Identifiers to thread into the produced Trace. Autogenerated if missing. */
  runId?: string;
  resultId?: string;
}

export interface RunnerResult {
  trace: Trace;
  toolCalls: ToolCall[];
  finalContent?: string;
  error?: string;
  durationMs: number;
}
