/* Import ASB's bundled fixture data (agents, tasks, tools) and emit ASP-X
 * TypeScript modules under packages/core/src/data/. Run with:
 *   pnpm tsx scripts/port-asb-data.mts /home/toni/zqy/ASB
 * Re-runnable; output files are fully overwritten.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const ASB_ROOT = process.argv[2] ?? "/home/toni/zqy/ASB";
const OUT_DIR = path.join(REPO_ROOT, "packages/core/src/data");

interface AsbAgentTask {
  agent_name: string;
  agent_path: string;
  tasks: string[];
}

interface AsbAgentConfig {
  name: string;
  description: string[];
  tools: string[];
}

interface AsbAttackTool {
  "Attacker Tool": string;
  "Attacker Instruction": string;
  Description: string;
  "Attack goal": string;
  "Attack Type": string;
  "Corresponding Agent": string;
  Aggressive: string;
}

interface AsbNormalTool {
  "Tool Name": string;
  Description: string;
  "Expected Achievements": string;
  "Corresponding Agent": string;
}

async function readJsonl<T>(file: string): Promise<T[]> {
  const raw = await fs.readFile(file, "utf8");
  return raw
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as T);
}

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await fs.readFile(file, "utf8")) as T;
}

function humanize(snake: string): string {
  return snake
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function tsLiteral(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

async function main() {
  console.log(`Reading ASB data from: ${ASB_ROOT}`);
  console.log(`Writing TS output to:  ${OUT_DIR}`);
  await fs.mkdir(OUT_DIR, { recursive: true });

  // 1. Agents (id + tasks).
  const agentTasks = await readJsonl<AsbAgentTask>(
    path.join(ASB_ROOT, "data/agent_task.jsonl"),
  );

  // 2. Per-agent config (role + normal tools list).
  type FlatAgent = {
    id: string;
    name: string;
    role: string;
    normal_tool_ids: string[];
    tasks: string[];
  };
  const agents: FlatAgent[] = [];
  for (const t of agentTasks) {
    const cfgPath = path.join(
      ASB_ROOT,
      "pyopenagi/agents",
      t.agent_path,
      "config.json",
    );
    let cfg: AsbAgentConfig;
    try {
      cfg = await readJson<AsbAgentConfig>(cfgPath);
    } catch (e) {
      console.warn(`Skipping ${t.agent_name}: ${(e as Error).message}`);
      continue;
    }
    agents.push({
      id: t.agent_name,
      name: humanize(t.agent_name),
      role: cfg.description.join(" ").trim(),
      // strip simulated_tools/ prefix if present
      normal_tool_ids: cfg.tools.map((s) => s.split("/").pop() ?? s),
      tasks: t.tasks,
    });
  }
  console.log(`Loaded ${agents.length} agents.`);

  // 3. Normal tools.
  const normalToolsRaw = await readJsonl<AsbNormalTool>(
    path.join(ASB_ROOT, "data/all_normal_tools.jsonl"),
  );
  const normalTools = normalToolsRaw.map((t) => ({
    id: t["Tool Name"],
    name: t["Tool Name"],
    description: t.Description,
    kind: "normal" as const,
    expected_achievement: t["Expected Achievements"],
    corresponding_agent: t["Corresponding Agent"],
  }));
  console.log(`Loaded ${normalTools.length} normal tools.`);

  // 4. Attack tools (all = agg + non-agg).
  const attackToolsRaw = await readJsonl<AsbAttackTool>(
    path.join(ASB_ROOT, "data/all_attack_tools.jsonl"),
  );
  const attackTools = attackToolsRaw.map((t) => ({
    id: t["Attacker Tool"],
    name: t["Attacker Tool"],
    description: t.Description,
    kind: "attack" as const,
    aggressive: t.Aggressive === "True" || t.Aggressive === "true",
    attack_instruction: t["Attacker Instruction"],
    expected_achievement: t["Attack goal"],
    attack_type: t["Attack Type"],
    corresponding_agent: t["Corresponding Agent"],
  }));
  console.log(`Loaded ${attackTools.length} attack tools.`);

  // 5. Emit agents.ts
  const agentsTs = `/* AUTO-GENERATED by scripts/port-asb-data.mts. Do not edit by hand. */
import type { AgentDef } from "@asp-x/shared";

/**
 * The 10 built-in industry agents ported from ASB.
 * Each agent's \`tool_ids\` lists only its normal tools.
 * Attack tools are added per-run by the runner based on the chosen attack target.
 */
export const AGENTS: readonly AgentDef[] = ${tsLiteral(
    agents.map((a) => ({
      id: a.id,
      name: a.name,
      role: a.role,
      tool_ids: a.normal_tool_ids,
      tasks: a.tasks,
    })),
  )} as const;
`;
  await fs.writeFile(path.join(OUT_DIR, "agents.ts"), agentsTs);

  // 6. Emit normal_tools.ts
  const normalToolsTs = `/* AUTO-GENERATED by scripts/port-asb-data.mts. Do not edit by hand. */
import type { ToolDef } from "@asp-x/shared";

export interface NormalToolEntry extends ToolDef {
  /** ASB metadata: which agent this normal tool belongs to. */
  corresponding_agent: string;
}

export const NORMAL_TOOLS: readonly NormalToolEntry[] = ${tsLiteral(normalTools)} as const;
`;
  await fs.writeFile(path.join(OUT_DIR, "normal_tools.ts"), normalToolsTs);

  // 7. Emit attack_tools.ts
  const attackToolsTs = `/* AUTO-GENERATED by scripts/port-asb-data.mts. Do not edit by hand. */
import type { ToolDef } from "@asp-x/shared";

export interface AttackToolEntry extends ToolDef {
  /** ASB metadata: which agent this attack targets. */
  corresponding_agent: string;
  /** ASB metadata: free-form attack-type label (e.g. "Stealthy Attack"). */
  attack_type: string;
}

export const ATTACK_TOOLS: readonly AttackToolEntry[] = ${tsLiteral(attackTools)} as const;
`;
  await fs.writeFile(path.join(OUT_DIR, "attack_tools.ts"), attackToolsTs);

  console.log("Done.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
